#ifndef BOLOS_CONFIG_H
#define BOLOS_CONFIG_H
#define SDK_VERSION "v2.1.0-6"
#define SDK_HASH "8b6fdc43b89ade975a032ddbe710ad872894956f"
#define gcc 
#define __IO volatile
#define NDEBUG 
#define HAVE_BAGL 
#define HAVE_SEED_COOKIE 
#define BAGL_WIDTH 128
#define BAGL_HEIGHT 32
#define HAVE_NES_CRYPT 
#define HAVE_ST_EDES_PLUS 
#define HAVE_ST_AES 
#define NATIVE_LITTLE_ENDIAN 
#define HAVE_CRC 
#define HAVE_HASH 
#define HAVE_RIPEMD160 
#define HAVE_SHA224 
#define HAVE_SHA256 
#define HAVE_SHA3 
#define HAVE_SHA384 
#define HAVE_SHA512 
#define HAVE_SHA512_WITH_BLOCK_ALT_METHOD 
#define HAVE_SHA512_WITH_BLOCK_ALT_METHOD_M0 
#define HAVE_BLAKE2 
#define HAVE_GROESTL 
#define HAVE_HMAC 
#define HAVE_PBKDF2 
#define HAVE_DES 
#define HAVE_AES 
#define HAVE_MATH 
#define HAVE_RNG 
#define HAVE_RNG_RFC6979 
#define HAVE_RNG_SP800_90A 
#define HAVE_ECC 
#define HAVE_ECC_WEIERSTRASS 
#define HAVE_ECC_TWISTED_EDWARDS 
#define HAVE_ECC_MONTGOMERY 
#define HAVE_SECP256K1_CURVE 
#define HAVE_SECP256R1_CURVE 
#define HAVE_SECP384R1_CURVE 
#define HAVE_SECP521R1_CURVE 
#define HAVE_FR256V1_CURVE 
#define HAVE_STARK256_CURVE 
#define HAVE_BRAINPOOL_P256R1_CURVE 
#define HAVE_BRAINPOOL_P256T1_CURVE 
#define HAVE_BRAINPOOL_P320R1_CURVE 
#define HAVE_BRAINPOOL_P320T1_CURVE 
#define HAVE_BRAINPOOL_P384R1_CURVE 
#define HAVE_BRAINPOOL_P384T1_CURVE 
#define HAVE_BRAINPOOL_P512R1_CURVE 
#define HAVE_BRAINPOOL_P512T1_CURVE 
#define HAVE_BLS12_381_G1_CURVE 
#define HAVE_CV25519_CURVE 
#define HAVE_CV448_CURVE 
#define HAVE_ED25519_CURVE 
#define HAVE_ED448_CURVE 
#define HAVE_ECDH 
#define HAVE_ECDSA 
#define HAVE_EDDSA 
#define HAVE_ECSCHNORR 
#define HAVE_X25519 
#define HAVE_X448 
#define APPNAME "Boilerplate"
#define APPVERSION "1.0.1"
#define MAJOR_VERSION 1
#define MINOR_VERSION 0
#define PATCH_VERSION 1
#define OS_IO_SEPROXYHAL 
#define HAVE_SPRINTF 
#define HAVE_SNPRINTF_FORMAT_U 
#define HAVE_IO_USB 
#define HAVE_L4_USBLIB 
#define IO_USB_MAX_ENDPOINTS 6
#define IO_HID_EP_LENGTH 64
#define HAVE_USB_APDU 
#define USB_SEGMENT_SIZE 64
#define BLE_SEGMENT_SIZE 32
#define HAVE_WEBUSB 
#define WEBUSB_URL_SIZE_B 0
#define WEBUSB_URL 
#define UNUSED(x) (void)x
#define IO_SEPROXYHAL_BUFFER_SIZE_B 128
#define HAVE_BAGL 
#define HAVE_UX_FLOW 
#define PRINTF(...) 
#endif // BOLOS_CONFIG_H
